apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  name: {{ include "awsx-api.fullname" . }}
  labels:
    {{- include "awsx-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "awsx-api.selectorLabels" . | nindent 4 }}
